### ISSUE TITLE
Faulty encoding when using `getCleanTitle()`

### ISSUE THREAD

**Issue by Plugway** [s-frei/TrackSearch#139]
Hello. Found a problem with the encoding in the title of [this](https://www.youtube.com/watch?v=zPkG-eNQBd8) video. Perhaps this problem may also manifest in channel names. The `track.getCleanTitle()` method returns the string "Iglooghost - Rust GenomeгЂЊVisualiserгЂЌ". I was able to fix the encoding this way:
```Java
new String(input.getBytes("windows-1251"), StandardCharsets.UTF_8);
```
This results in the correct "Iglooghost - Rust Genome「Visualiser」" string.

If this matters: I'm using Java SDK 17 on Windows 10.

**Comment by s-frei** [comment]
Hi there, will have a look at this the next days 🙂 Thanks for letting me know!

**Comment by s-frei** [comment]
@Plugway I cannot verify the behaviour you described. Everything seems to work and look correct on my side.
<img width="729" alt="grafik" src="https://github.com/s-frei/TrackSearch/assets/25681388/2d800c56-c513-4ecb-a559-2ad3fc995720">
Are you sure the method `getCleanTitle()` is the appropriate for you? You could use `getTitle()` instead.
