### ISSUE TITLE
FeatureRequest: Get related videos.

### ISSUE THREAD

**Issue by MrF1yn** [s-frei/TrackSearch#91]
A method to fetch related videos which takes in the video URL and gives the list of related tracks, by opening the url and getting the videos which is displayed in the right side of the video player.

**Comment by s-frei** [comment]
For sure a good idea. But currently, as soon as I have time for this project, I would prefer to parse playlists.
But If you feel like, give it a go 😉

**Comment by s-frei** [comment]
See PR
